apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: task-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: <ECR_REPO_URL>/task-worker:latest
          envFrom:
            - configMapRef:
                name: task-config
            - secretRef:
                name: task-secrets
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
